package exception;

class Test6 {
	
	void method1() throws Exception{
		String str = null;
		System.out.println(str.charAt(0));
	}
	
	void method2() throws Exception{
		int[] arr = {2, 7, 8, 4, 6};
		System.out.println(arr[5]);
	}
}

public class Ex06 {
	public static void main(String[] args) throws Exception{
		// throws : 현재 함수에서 발생한 예외의 처리를 caller에게 전가시킨다
		
		Test6 ob = new Test6();
		ob.method1();
		ob.method2();
	}

}
